name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - main  # Or your main branch name
# Define as permissões necessárias para o GitHub Pages
permissions:
  contents: write # Permite gravar o conteúdo do repositório
  pages: write   # Permite escrever na branch de pages
  id-token: write # Necessário para autenticação OIDC (segurança)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build and publish Blazor app
        run: |
          dotnet publish ./ScreenSound.WebAssembly/ScreenSound.WebAssembly.csproj -c Release -o ./publish
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./publish/wwwroot
          branch: gh-pages
          clean: true

